package src.CodeGenerator;

import src.SyntacticalAnalyzer.ASTNode;
import src.SyntacticalAnalyzer.Visitor;
import src.SemanticAnalyzer.SymbolTable;
import src.SemanticAnalyzer.SymbolTableEntry;
import java.util.*;

/**
 * Moon code generator — the final pass of the compiler (Pass 4).
 *
 * This visitor walks the AST and emits Moon assembly instructions. It relies on
 * ComputeMemSizeVisitor (Pass 3) having already annotated every SymbolTableEntry
 * with size/offset values, and every SymbolTable scope with its total scopeSize.
 *
 * The output is a complete .moon file: executable instructions, data reservations,
 * and the inline I/O library (putstr, getstr, intstr, strint).
 *
 * Moon register conventions:
 *   r0  = hardwired to 0 (useful for loading immediates: addi r1,r0,42)
 *   r1-r12 = general-purpose register pool (allocated/freed on demand)
 *   r13 = function return value (caller reads it after jl; callee writes it before jr)
 *   r14 = stack pointer — initialized to topaddr, grows downward on each function call
 *   r15 = return-address link — set by jl (jump-and-link), consumed by jr r15
 *
 * Stack frame layout (negative offsets from r14):
 *   -4(r14)           : saved return address (r15) — every function stores it here at entry
 *   -8(r14)           : hidden 'self' pointer (member functions only) OR first parameter
 *   -(8+paramBytes)   : parameters laid out in declaration order
 *   -(8+paramBytes+localBytes) : local variables laid out in declaration order
 *   remaining 200 bytes: scratch space for library sub-calls (intstr/putstr etc.)
 *
 * The total frame size (scopeSize) is pre-computed by ComputeMemSizeVisitor.
 * When calling a function, the caller does:  subi r14,r14,scopeSize  (push frame)
 * When the call returns, the caller does:    addi r14,r14,scopeSize  (pop frame)
 */
public class CodeGenerator implements Visitor {

    /** The global symbol table — used to look up classes and free functions. */
    private final SymbolTable globalTable;

    /**
     * Maps AST nodes (FuncDef, ProgBlock) to their corresponding SymbolTable scopes.
     * Built during Pass 1 (SymbolTableBuilder). Used here to find the scope for each
     * function body or main block so we can read parameter/local offsets.
     */
    private final Map<ASTNode, SymbolTable> funcTableMap;

    /**
     * Two separate output buffers that get concatenated in getMoonCode():
     *   execCode — all executable instructions (entry, main, functions)
     *   dataCode — data directives (res for buffers/globals) and the inline library
     */
    private final StringBuilder execCode = new StringBuilder();
    private final StringBuilder dataCode = new StringBuilder();

    /** The symbol table for the function/main block currently being generated. */
    private SymbolTable currentScope;

    /** Counter for unique data labels (buf0, buf1, objret2, ...). */
    private int tempCounter = 0;

    /** Counter for unique control-flow labels (while0, else1, endif2, ...). */
    private int labelCounter = 0;

    public CodeGenerator(SymbolTable globalTable, Map<ASTNode, SymbolTable> funcTableMap) {
        this.globalTable = globalTable;
        this.funcTableMap = funcTableMap;
    }

    // ==================== Entry Point ====================

    /**
     * Visitor entry point — only acts on the root "Prog" node.
     * Emits the complete Moon program in this order:
     *   1. Program header (entry point, stack pointer init)
     *   2. Main block code
     *   3. hlt instruction
     *   4. All function definitions (placed after hlt so they're only reached via jl)
     *   5. Data section (reserved buffers, global variables)
     *   6. Inline library routines (putstr, getstr, intstr, strint)
     */
    @Override
    public void visit(ASTNode node) {
        if (!"Prog".equals(node.getType())) return;

        // The Prog node has three children: [ClassList, FuncDefList, ProgBlock]
        ASTNode funcDefList = node.getChildren().get(1);
        ASTNode progBlock = node.getChildren().get(2);

        // --- 1. Program header ---
        emit("", "", "% ==========================================");
        emit("", "", "% Moon code generated by comp442 compiler");
        emit("", "", "% ==========================================");
        emit("", "entry", "");
        // topaddr is a Moon built-in symbol for the highest memory address.
        // The stack starts here and grows downward.
        emit("", "addi r14,r0,topaddr", "% Initialize stack pointer");

        // --- 2. Main block ---
        generateMain(progBlock);

        // --- 3. Halt ---
        emit("", "hlt", "% End of program");

        // --- 4. Function definitions ---
        // These are placed after hlt. They're only executed when called via jl.
        if (funcDefList.getChildren() != null) {
            for (ASTNode fd : funcDefList.getChildren()) {
                generateFuncDef(fd);
            }
        }

        // --- 5 & 6. Data section + library ---
        dataCode.append("\n% ==========================================\n");
        dataCode.append("% Data Section\n");
        dataCode.append("% ==========================================\n");
        emitLibrary();
    }

    /**
     * Returns the complete Moon program as a string.
     * execCode (instructions) comes first, then dataCode (data + library).
     */
    public String getMoonCode() {
        return execCode.toString() + dataCode.toString();
    }

    /**
     * Convenience wrapper: computes the byte size of a type string (e.g., "int", "int[3]", "MyClass").
     * Delegates to ComputeMemSizeVisitor.typeSize() since it already has the sizing logic.
     */
    private int typeSize(String type) {
        ComputeMemSizeVisitor sizer = new ComputeMemSizeVisitor(globalTable);
        return sizer.typeSize(type);
    }

    // ==================== Main Block ====================

    /**
     * Generates code for the program's main block.
     * Main is special: r14 stays at topaddr (no frame push needed because nobody called us).
     * Local variables are accessed via negative offsets from r14 directly.
     * VarDecl nodes are skipped — they only declare storage which is handled by offsets.
     */
    private void generateMain(ASTNode progBlock) {
        // Look up main's symbol table — try the funcTableMap first, fall back to global search
        SymbolTable mt = funcTableMap.get(progBlock);
        if (mt == null) {
            for (SymbolTableEntry e : globalTable.getEntries())
                if ("function".equals(e.getKind()) && "main".equals(e.getName())) { mt = e.getLink(); break; }
        }
        if (mt == null) return;
        currentScope = mt;

        emit("", "", "% ---- main ----");

        // Walk each child statement (skip VarDecl nodes — they don't generate code)
        if (progBlock.getChildren() != null) {
            for (ASTNode child : progBlock.getChildren()) {
                if (!"VarDecl".equals(child.getType())) {
                    generateStatement(child);
                }
            }
        }
    }

    // ==================== Function Definitions ====================

    /**
     * Generates code for a free function or member function definition.
     *
     * Emitted structure:
     *   label:                        % Function entry
     *     sw -4(r14),r15              % Save return address (prologue)
     *     ... body statements ...
     *   label_end:                    % Epilogue (reached by fall-through or explicit return)
     *     lw r15,-4(r14)             % Restore return address
     *     jr r15                     % Jump back to caller
     *
     * The label is derived from the scope name: "::funcName" for free functions,
     * "ClassName::funcName" for member functions, sanitized to valid Moon label chars.
     */
    private void generateFuncDef(ASTNode node) {
        ASTNode funcHead = node.getChildren().get(0);
        ASTNode funcBody = node.getChildren().get(1);

        // Look up this function's symbol table scope
        SymbolTable ft = funcTableMap.get(node);
        if (ft == null) return;
        currentScope = ft;

        String label = sanitizeLabel(ft.getName());

        // Prologue: emit label and save the return address
        emit("", "", "% ---- function " + ft.getName() + " ----");
        emit(label, "", "% Function entry");
        emit("", "sw -4(r14),r15", "% Save return address");

        // Body: generate each statement (VarDecls handled by offsets, not code)
        ASTNode statList = funcBody.getChildren().get(1);
        if (statList != null && statList.getChildren() != null) {
            for (ASTNode s : statList.getChildren()) {
                generateStatement(s);
            }
        }

        // Epilogue: restore return address and jump back.
        // Even if every path has an explicit return, we emit this as a safe landing pad.
        emit(label + "_end", "lw r15,-4(r14)", "% Restore return address");
        emit("", "jr r15", "% Return");
    }

    // ==================== Statement Generation ====================

    /**
     * Top-level statement dispatcher. Examines the AST node type and delegates to
     * the appropriate generator method. StatBlock/StatList nodes recurse into children.
     */
    private void generateStatement(ASTNode node) {
        if (node == null) return;
        switch (node.getType()) {
            case "AssignStat": generateAssign(node); break;
            case "IfStat": generateIf(node); break;
            case "WhileStat": generateWhile(node); break;
            case "WriteStat": generateWrite(node); break;
            case "ReadStat": generateRead(node); break;
            case "ReturnStat": generateReturn(node); break;
            case "FuncCall": generateFuncCallStatement(node); break;
            case "Dot": generateExpr(node); break; // e.g., obj.method() as a statement
            case "StatBlock": case "StatList":
                if (node.getChildren() != null)
                    for (ASTNode c : node.getChildren()) generateStatement(c);
                break;
            default: break;
        }
    }

    // ---- 3.1 Assignment (rubric item 3.1) ----

    /**
     * Generates code for an assignment statement: LHS = RHS.
     *
     * Simple case (scalar): evaluate RHS into a register, compute LHS address, sw.
     * Object case (class type returned from member function): the function returns an
     * address in r13, and we copy word-by-word from that address into the LHS.
     */
    private void generateAssign(ASTNode node) {
        ASTNode lhs = node.getChildren().get(0); // DataMember or Dot
        ASTNode rhs = node.getChildren().get(1); // expression

        emit("", "", "% Assignment statement (line " + node.getLineNumber() + ")");

        // Check if LHS is an object type (class) — may need object copy
        String lhsType = inferTypeForCodeGen(lhs);
        boolean isObjectAssign = (lhsType != null && isClassType(lhsType));

        // Check if RHS is a Dot->FuncCall returning an object (member func call returning object)
        boolean rhsReturnObject = false;
        if ("Dot".equals(rhs.getType()) && rhs.getChildren().size() >= 2
                && "FuncCall".equals(rhs.getChildren().get(1).getType())) {
            String rhsType = inferTypeForCodeGen(rhs);
            if (rhsType != null && isClassType(rhsType)) rhsReturnObject = true;
        }

        if (isObjectAssign && rhsReturnObject) {
            // For object returns from member functions, we use a two-step approach:
            // 1. Before the call, pass the LHS address as a "return destination"
            // 2. The callee copies its local object to that destination before returning
            // Since this is complex, we use a simpler approach:
            // Call the function, then copy from the returned address in the callee's frame
            // We handle this by doing the copy INSIDE the frame before deallocation
            // For now: call, get address, copy to LHS using the buffer area

            // Get LHS address first
            String lhsAddrReg = generateLhsAddress(lhs);
            // Save LHS address to a temp spot
            String tempLabel = newDataLabel("objret");
            dataCode.append(tempLabel).append(" res 4\n");
            emit("", "sw " + tempLabel + "(r0)," + lhsAddrReg, "% Save LHS addr for object copy");
            freeReg(lhsAddrReg);

            // Call the function — it returns object address in r13
            String rhsReg = generateExpr(rhs);

            // Reload LHS address and copy object
            lhsAddrReg = allocReg();
            emit("", "lw " + lhsAddrReg + "," + tempLabel + "(r0)", "% Reload LHS addr for object copy");
            int objSize = 4;
            if (lhsType != null) objSize = typeSize(lhsType);
            for (int off = 0; off < objSize; off += 4) {
                String tmpReg = allocReg();
                emit("", "lw " + tmpReg + "," + off + "(" + rhsReg + ")", "% Copy object word at offset " + off);
                emit("", "sw " + off + "(" + lhsAddrReg + ")," + tmpReg, "% Store to dest at offset " + off);
                freeReg(tmpReg);
            }
            freeReg(rhsReg);
            freeReg(lhsAddrReg);
        } else {
            // Simple value assignment
            String rhsReg = generateExpr(rhs);
            String lhsAddrReg = generateLhsAddress(lhs);
            emit("", "sw 0(" + lhsAddrReg + ")," + rhsReg, "% Store assignment value");
            freeReg(rhsReg);
            freeReg(lhsAddrReg);
        }
    }

    // ---- 3.2 If-then-else (rubric item 3.2) ----

    /**
     * Generates:  evaluate condition → bz else → then-block → j endif → else-block → endif
     * The condition expression evaluates to 1 (true) or 0 (false).
     * bz (branch-if-zero) jumps to else when the condition is false.
     */
    private void generateIf(ASTNode node) {
        ASTNode cond = node.getChildren().get(0);
        ASTNode thenBlock = node.getChildren().get(1);
        ASTNode elseBlock = node.getChildren().get(2);

        String elseLabel = newLabel("else");
        String endifLabel = newLabel("endif");

        emit("", "", "% if statement (line " + node.getLineNumber() + ")");

        // Evaluate condition
        String condReg = generateExpr(cond);
        emit("", "bz " + condReg + "," + elseLabel, "% Branch to else if false");
        freeReg(condReg);

        // Then block
        generateStatement(thenBlock);
        emit("", "j " + endifLabel, "% Jump past else");

        // Else block
        emit(elseLabel, "", "% else branch");
        generateStatement(elseBlock);

        emit(endifLabel, "", "% end if");
    }

    // ---- 3.3 While loop (rubric item 3.3) ----

    /**
     * Generates:  whileN → evaluate condition → bz endwhileN → body → j whileN → endwhileN
     * The loop label is placed before the condition so we re-evaluate every iteration.
     */
    private void generateWhile(ASTNode node) {
        ASTNode cond = node.getChildren().get(0);
        ASTNode body = node.getChildren().get(1);

        String loopLabel = newLabel("while");
        String endLabel = newLabel("endwhile");

        emit("", "", "% while loop (line " + node.getLineNumber() + ")");
        emit(loopLabel, "", "% Loop start");

        // Evaluate condition
        String condReg = generateExpr(cond);
        emit("", "bz " + condReg + "," + endLabel, "% Exit loop if false");
        freeReg(condReg);

        // Loop body
        generateStatement(body);
        emit("", "j " + loopLabel, "% Jump back to loop start");

        emit(endLabel, "", "% End while");
    }

    // ---- 3.4 Write (rubric item 3.4) ----

    /**
     * Generates code for write(expr):
     *   1. Evaluate the expression to get an integer value in a register.
     *   2. Reserve a 20-byte buffer in the data section for the string conversion.
     *   3. Call intstr (integer→string): pass value at -8, buffer at -12 of a sub-frame.
     *   4. Call putstr (print string): pass the string address (r13) at -8 of a sub-frame.
     *   5. Emit a newline character via putc.
     *
     * The "sub-frame" technique: we push r14 down by the current scope's frame size
     * before calling the library, so the library's -8(r14)/-12(r14) params don't
     * collide with our local variables. After the library returns, we restore r14.
     */
    private void generateWrite(ASTNode node) {
        ASTNode expr = node.getChildren().get(0);
        emit("", "", "% write statement (line " + node.getLineNumber() + ")");

        // Step 1: evaluate expression
        String valReg = generateExpr(expr);

        // Step 2: reserve a string buffer in the data section
        String bufLabel = newDataLabel("buf");
        dataCode.append(bufLabel).append(" res 20\n");

        // Step 3: call intstr(value, buffer) → r13 = pointer to result string
        int libFrame = getLibCallOffset();
        emit("", "sw " + (-8 - libFrame) + "(r14)," + valReg, "% Pass value to intstr");
        emit("", "addi " + valReg + ",r0," + bufLabel, "% Load buffer address");
        emit("", "sw " + (-12 - libFrame) + "(r14)," + valReg, "% Pass buffer to intstr");
        emit("", "subi r14,r14," + libFrame, "% Allocate lib call frame");
        emit("", "jl r15,intstr", "% Convert int to string");
        emit("", "addi r14,r14," + libFrame, "% Deallocate lib call frame");

        // Step 4: call putstr(r13) to print the string
        emit("", "sw " + (-8 - libFrame) + "(r14),r13", "% Pass string to putstr");
        emit("", "subi r14,r14," + libFrame, "% Allocate lib call frame");
        emit("", "jl r15,putstr", "% Print the string");
        emit("", "addi r14,r14," + libFrame, "% Deallocate lib call frame");

        // Step 5: print newline
        String nlReg = allocReg();
        emit("", "addi " + nlReg + ",r0,10", "% Newline character (ASCII 10)");
        emit("", "putc " + nlReg, "% Output newline");
        freeReg(nlReg);
        freeReg(valReg);
    }

    // ---- 3.4 Read (rubric item 3.4) ----

    /**
     * Generates code for read(var):
     *   1. Reserve a buffer, call getstr to read a line of keyboard input into it.
     *   2. Call strint to convert the string to an integer (result in r13).
     *   3. Store r13 into the target variable.
     */
    private void generateRead(ASTNode node) {
        ASTNode var = node.getChildren().get(0);
        emit("", "", "% read statement (line " + node.getLineNumber() + ")");

        String bufLabel = newDataLabel("rbuf");
        dataCode.append(bufLabel).append(" res 20\n");

        int libFrame = getLibCallOffset();
        String addrReg = allocReg();
        emit("", "addi " + addrReg + ",r0," + bufLabel, "% Load buffer address");
        emit("", "sw " + (-8 - libFrame) + "(r14)," + addrReg, "% Pass buffer to getstr");
        emit("", "subi r14,r14," + libFrame, "% Allocate lib call frame");
        emit("", "jl r15,getstr", "% Read string from keyboard");
        emit("", "addi r14,r14," + libFrame, "% Deallocate lib call frame");

        // Convert string to integer
        emit("", "addi " + addrReg + ",r0," + bufLabel, "% Reload buffer address");
        emit("", "sw " + (-8 - libFrame) + "(r14)," + addrReg, "% Pass buffer to strint");
        emit("", "subi r14,r14," + libFrame, "% Allocate lib call frame");
        emit("", "jl r15,strint", "% Convert string to integer");
        emit("", "addi r14,r14," + libFrame, "% Deallocate lib call frame");
        freeReg(addrReg);

        // Store r13 (result) into the variable
        String lhsAddr = generateLhsAddress(var);
        emit("", "sw 0(" + lhsAddr + "),r13", "% Store read value into variable");
        freeReg(lhsAddr);
    }

    // ---- Return statement (rubric item 2.3) ----

    /**
     * Generates code for return(expr):
     *   1. Evaluate the expression and put the result in r13 (the return value register).
     *   2. Jump to the function's epilogue label (funcLabel_end), which restores r15 and returns.
     *
     * Special case for object returns: instead of returning a value, we return the
     * object's memory address in r13 so the caller can copy the object's contents.
     */
    private void generateReturn(ASTNode node) {
        ASTNode expr = node.getChildren().get(0);
        emit("", "", "% return statement (line " + node.getLineNumber() + ")");

        if (!"Epsilon".equals(expr.getType())) {
            // Check if returning a class-typed object — return its address, not its value
            String retType = getReturnTypeOfCurrentFunc();
            if (retType != null && isClassType(retType) && "DataMember".equals(expr.getType())) {
                String addrReg = generateVarAddress(expr);
                emit("", "add r13,r0," + addrReg, "% Set return value (object address) in r13");
                freeReg(addrReg);
            } else {
                // Scalar return — evaluate and move to r13
                String valReg = generateExpr(expr);
                emit("", "add r13,r0," + valReg, "% Set return value in r13");
                freeReg(valReg);
            }
        }

        // Don't emit lw/jr here — jump to the shared epilogue at the function's end
        String funcLabel = sanitizeLabel(currentScope.getName());
        emit("", "j " + funcLabel + "_end", "% Jump to function epilogue");
    }

    // ==================== Expression Generation ====================

    /**
     * Central expression dispatcher. Recursively evaluates an AST expression node and
     * returns the name of the register holding the result (e.g., "r3").
     *
     * The caller is responsible for calling freeReg() on the returned register when done.
     * Each sub-method allocates a result register, evaluates operands, and frees operand registers.
     */
    private String generateExpr(ASTNode node) {
        if (node == null) return allocRegWithValue(0);
        switch (node.getType()) {
            case "IntNum": return generateIntLiteral(node);
            case "FloatNum": return generateFloatLiteral(node);
            case "DataMember": return generateDataMemberLoad(node);
            case "AddOp": return generateAddOp(node);
            case "MultOp": return generateMultOp(node);
            case "RelExpr": return generateRelExpr(node);
            case "Sign": return generateSign(node);
            case "Not": return generateNot(node);
            case "FuncCall": return generateFuncCallExpr(node, null);
            case "Dot": return generateDotExpr(node);
            case "Epsilon": return allocRegWithValue(0);
            default:
                // If it has children, try evaluating first child
                if (node.getChildren() != null && !node.getChildren().isEmpty())
                    return generateExpr(node.getChildren().get(0));
                return allocRegWithValue(0);
        }
    }

    // ---- Literals ----

    /** Loads an integer literal into a register: addi rN,r0,value */
    private String generateIntLiteral(ASTNode node) {
        String reg = allocReg();
        int val = 0;
        try { val = Integer.parseInt(node.getValue()); } catch (Exception e) {}
        emit("", "addi " + reg + ",r0," + val, "% Load integer literal " + val);
        return reg;
    }

    /**
     * Loads a float literal as a scaled integer (value * 100).
     * Moon has no floating-point hardware, so 3.14 becomes 314.
     */
    private String generateFloatLiteral(ASTNode node) {
        String reg = allocReg();
        float fval = 0;
        try { fval = Float.parseFloat(node.getValue()); } catch (Exception e) {}
        int ival = Math.round(fval * 100);
        emit("", "addi " + reg + ",r0," + ival, "% Load float literal " + node.getValue() + " (as int*100=" + ival + ")");
        return reg;
    }

    // ---- 5.1 Arithmetic Expressions (rubric item 5.1) ----

    /**
     * Generates add/subtract/or: evaluate left and right recursively, then combine.
     * Children: [leftExpr, rightExpr], value = operator string ("+", "-", "or").
     */
    private String generateAddOp(ASTNode node) {
        String leftReg = generateExpr(node.getChildren().get(0));
        String rightReg = generateExpr(node.getChildren().get(1));
        String resultReg = allocReg();
        String op = node.getValue();
        switch (op) {
            case "+":
                emit("", "add " + resultReg + "," + leftReg + "," + rightReg, "% Addition");
                break;
            case "-":
                emit("", "sub " + resultReg + "," + leftReg + "," + rightReg, "% Subtraction");
                break;
            case "or":
                emit("", "or " + resultReg + "," + leftReg + "," + rightReg, "% Logical OR");
                break;
            default:
                emit("", "add " + resultReg + "," + leftReg + "," + rightReg, "% " + op);
                break;
        }
        freeReg(leftReg);
        freeReg(rightReg);
        return resultReg;
    }

    /** Generates multiply/divide/and — same pattern as addOp. */
    private String generateMultOp(ASTNode node) {
        String leftReg = generateExpr(node.getChildren().get(0));
        String rightReg = generateExpr(node.getChildren().get(1));
        String resultReg = allocReg();
        String op = node.getValue();
        switch (op) {
            case "*":
                emit("", "mul " + resultReg + "," + leftReg + "," + rightReg, "% Multiplication");
                break;
            case "/":
                emit("", "div " + resultReg + "," + leftReg + "," + rightReg, "% Division");
                break;
            case "and":
                emit("", "and " + resultReg + "," + leftReg + "," + rightReg, "% Logical AND");
                break;
            default:
                emit("", "mul " + resultReg + "," + leftReg + "," + rightReg, "% " + op);
                break;
        }
        freeReg(leftReg);
        freeReg(rightReg);
        return resultReg;
    }

    // ---- 5.1 Relational Expressions ----

    /**
     * Generates comparison: evaluates left and right, then uses Moon compare instructions
     * (clt, cgt, ceq, cne, cle, cge). Result is 1 (true) or 0 (false) in the result register.
     * Children: [leftExpr, relOpNode, rightExpr] where relOpNode.getValue() is "<", ">", etc.
     */
    private String generateRelExpr(ASTNode node) {
        ASTNode leftNode = node.getChildren().get(0);
        ASTNode relOp = node.getChildren().get(1);
        ASTNode rightNode = node.getChildren().get(2);

        String leftReg = generateExpr(leftNode);
        String rightReg = generateExpr(rightNode);
        String resultReg = allocReg();

        String op = relOp.getValue();
        switch (op) {
            case "<":  emit("", "clt " + resultReg + "," + leftReg + "," + rightReg, "% Less than"); break;
            case ">":  emit("", "cgt " + resultReg + "," + leftReg + "," + rightReg, "% Greater than"); break;
            case "<=": emit("", "cle " + resultReg + "," + leftReg + "," + rightReg, "% Less or equal"); break;
            case ">=": emit("", "cge " + resultReg + "," + leftReg + "," + rightReg, "% Greater or equal"); break;
            case "==": emit("", "ceq " + resultReg + "," + leftReg + "," + rightReg, "% Equal"); break;
            case "<>": case "!=":
                emit("", "cne " + resultReg + "," + leftReg + "," + rightReg, "% Not equal"); break;
            default:
                emit("", "ceq " + resultReg + "," + leftReg + "," + rightReg, "% " + op); break;
        }
        freeReg(leftReg);
        freeReg(rightReg);
        return resultReg;
    }

    private String generateSign(ASTNode node) {
        String inner = generateExpr(node.getChildren().get(0));
        if ("-".equals(node.getValue())) {
            String resultReg = allocReg();
            emit("", "sub " + resultReg + ",r0," + inner, "% Negate");
            freeReg(inner);
            return resultReg;
        }
        return inner;
    }

    private String generateNot(ASTNode node) {
        String inner = generateExpr(node.getChildren().get(0));
        String resultReg = allocReg();
        emit("", "not " + resultReg + "," + inner, "% Logical NOT");
        freeReg(inner);
        return resultReg;
    }

    // ==================== Variable Access ====================
    // These methods handle rubric items 4.1-4.4 (array access, object member access)
    // and 5.2-5.3 (array index expressions, object member expressions).

    /**
     * Loads a DataMember (simple variable or array element) into a register.
     * Computes the variable's address, then emits lw to load its value.
     */
    private String generateDataMemberLoad(ASTNode node) {
        String addrReg = generateVarAddress(node);
        String valReg = allocReg();
        emit("", "lw " + valReg + ",0(" + addrReg + ")", "% Load variable value");
        freeReg(addrReg);
        return valReg;
    }

    /**
     * Returns a register holding the memory address of the LHS of an assignment.
     * Dispatches to generateDotAddress for dot expressions (obj.member = ...),
     * or generateVarAddress for simple variables and array elements.
     */
    private String generateLhsAddress(ASTNode node) {
        if ("Dot".equals(node.getType())) {
            return generateDotAddress(node);
        }
        return generateVarAddress(node);
    }

    /**
     * Computes the memory address of a variable (DataMember node) and returns the register.
     *
     * This is the most complex addressing method. It handles four cases based on the
     * variable's kind (from the symbol table entry):
     *
     *   1. Stack local/param:  addi rN,r14,offset   (stack pointer + pre-computed offset)
     *   2. Ref param (array/object passed by reference):  lw rN,offset(r14)
     *      (the stack slot holds an ADDRESS, not a value — we load that address)
     *   3. Class data member (inside a member function):  lw rN,-8(r14)  then add member offset
     *      (follows the hidden 'self' pointer to reach the object's memory)
     *   4. Global fallback: allocates a labeled slot in the data section.
     *
     * After computing the base address, if the DataMember has index expressions
     * (e.g., arr[i+1][j]), each index is evaluated and multiplied by the element size
     * to produce the final address. This handles rubric items 4.1 and 5.2.
     */
    private String generateVarAddress(ASTNode node) {
        String name = node.getChildren().get(0).getValue();
        ASTNode indiceList = node.getChildren().get(1);

        // Look up variable in symbol table
        SymbolTableEntry entry = lookupVar(name, currentScope);
        String addrReg = allocReg();

        if (entry != null) {
            int offset = entry.getOffset();
            boolean isRefParam = "param".equals(entry.getKind()) &&
                    (entry.getType().contains("[") || isClassType(entry.getType()));

            if ("data".equals(entry.getKind()) && isMemberFunction(currentScope)) {
                // Class data member accessed from inside a member function
                // The 'self' object pointer is at -8(r14)
                String className = getMemberFuncClassName(currentScope);
                SymbolTableEntry classEntry = findClass(className);
                int memberOffset = 0;
                if (classEntry != null && classEntry.getLink() != null) {
                    memberOffset = computeMemberOffset(classEntry.getLink(), name);
                }
                emit("", "lw " + addrReg + ",-8(r14)", "% Load self pointer");
                if (memberOffset > 0) {
                    emit("", "addi " + addrReg + "," + addrReg + "," + memberOffset,
                            "% Offset to data member " + name);
                }
            } else if (offset != 0) {
                if (isRefParam) {
                    // Array/object parameter passed by reference — load the address from the stack
                    emit("", "lw " + addrReg + "," + offset + "(r14)", "% Load ref param address of " + name);
                } else {
                    // Stack variable — compute address as r14 + offset
                    emit("", "addi " + addrReg + ",r14," + offset, "% Address of " + name);
                }
            } else {
                // Use a global data label as fallback
                String label = newDataLabelFor(name);
                emit("", "addi " + addrReg + ",r0," + label, "% Address of global " + name);
            }

            // Handle array indexing (4.1, 5.2)
            if (indiceList != null && indiceList.getChildren() != null && !indiceList.getChildren().isEmpty()) {
                String type = entry.getType();
                int elementSize = getElementSize(type);
                List<Integer> dims = getDimensions(type);

                for (int i = 0; i < indiceList.getChildren().size(); i++) {
                    ASTNode indexExpr = indiceList.getChildren().get(i);
                    String indexReg = generateExpr(indexExpr);

                    // For multidimensional: multiply by product of remaining dimensions
                    int multiplier = elementSize;
                    for (int j = i + 1; j < dims.size(); j++) {
                        multiplier *= dims.get(j);
                    }

                    String offsetReg = allocReg();
                    emit("", "muli " + offsetReg + "," + indexReg + "," + multiplier, "% Index offset (* " + multiplier + ")");
                    emit("", "add " + addrReg + "," + addrReg + "," + offsetReg, "% Add index offset to base address");
                    freeReg(indexReg);
                    freeReg(offsetReg);
                }
            }
        } else {
            // Variable not found — emit a placeholder
            String label = newDataLabelFor(name);
            emit("", "addi " + addrReg + ",r0," + label, "% Address of " + name + " (fallback)");
        }

        return addrReg;
    }

    // ---- 4.3, 4.4, 5.3: Dot access (rubric items 4.3, 4.4, 5.3) ----

    /**
     * Evaluates a dot expression (e.g., obj.member or obj.method()).
     * If the right side is a FuncCall, delegates to generateMemberFuncCall (rubric 2.4).
     * Otherwise, computes the member address and loads the value (rubric 4.3/4.4).
     */
    private String generateDotExpr(ASTNode node) {
        ASTNode left = node.getChildren().get(0);
        ASTNode right = node.getChildren().get(1);

        if ("FuncCall".equals(right.getType())) {
            // Member function call (2.4)
            return generateMemberFuncCall(node);
        }

        // Data member access
        String addrReg = generateDotAddress(node);
        String valReg = allocReg();
        emit("", "lw " + valReg + ",0(" + addrReg + ")", "% Load member value via dot");
        freeReg(addrReg);
        return valReg;
    }

    /**
     * Computes the memory address of a dot chain (e.g., obj.member, obj.inner.val).
     * Recursively resolves the left side to get the base object address, then adds
     * the member's offset within the class. Handles nested objects (4.4) via recursion.
     * Also handles array indexing on members (e.g., obj.arr[i]).
     */
    private String generateDotAddress(ASTNode node) {
        ASTNode left = node.getChildren().get(0);
        ASTNode right = node.getChildren().get(1);

        // Get address of the left object
        String baseAddrReg;
        if ("Dot".equals(left.getType())) {
            baseAddrReg = generateDotAddress(left);
        } else if ("DataMember".equals(left.getType())) {
            baseAddrReg = generateVarAddress(left);
        } else {
            baseAddrReg = generateExpr(left);
        }

        // Get the type of the left object to find member offset
        String leftType = inferTypeForCodeGen(left);
        if (leftType != null) {
            SymbolTableEntry classEntry = findClass(leftType);
            if (classEntry != null && classEntry.getLink() != null) {
                String memberName;
                if ("DataMember".equals(right.getType())) {
                    memberName = right.getChildren().get(0).getValue();
                } else {
                    memberName = right.getChildren() != null && !right.getChildren().isEmpty() ?
                            right.getChildren().get(0).getValue() : "";
                }
                int memberOffset = computeMemberOffset(classEntry.getLink(), memberName);
                if (memberOffset > 0) {
                    emit("", "addi " + baseAddrReg + "," + baseAddrReg + "," + memberOffset,
                            "% Offset to member " + memberName);
                }

                // Handle array indexing on the member
                if ("DataMember".equals(right.getType())) {
                    ASTNode indiceList = right.getChildren().get(1);
                    if (indiceList != null && indiceList.getChildren() != null && !indiceList.getChildren().isEmpty()) {
                        SymbolTableEntry memberEntry = classEntry.getLink().lookupLocal(memberName, "data");
                        if (memberEntry == null) memberEntry = classEntry.getLink().lookupInherited(memberName, "data");
                        if (memberEntry != null) {
                            int elemSize = getElementSize(memberEntry.getType());
                            List<Integer> dims = getDimensions(memberEntry.getType());
                            for (int i = 0; i < indiceList.getChildren().size(); i++) {
                                String idxReg = generateExpr(indiceList.getChildren().get(i));
                                int mult = elemSize;
                                for (int j = i + 1; j < dims.size(); j++) mult *= dims.get(j);
                                String offReg = allocReg();
                                emit("", "muli " + offReg + "," + idxReg + "," + mult, "% Array member index offset");
                                emit("", "add " + baseAddrReg + "," + baseAddrReg + "," + offReg, "% Add array offset");
                                freeReg(idxReg);
                                freeReg(offReg);
                            }
                        }
                    }
                }
            }
        }

        return baseAddrReg;
    }

    /**
     * Looks up a data member's byte offset within a class, checking inherited tables first.
     * Returns the offset value that was pre-computed by ComputeMemSizeVisitor.
     */
    private int computeMemberOffset(SymbolTable classTable, String memberName) {
        for (SymbolTable inh : classTable.getInheritedTables()) {
            SymbolTableEntry e = inh.lookupLocal(memberName, "data");
            if (e != null) return e.getOffset();
            int deepOff = computeMemberOffset(inh, memberName);
            if (deepOff >= 0) return deepOff;
        }
        // Then own data members
        SymbolTableEntry e = classTable.lookupLocal(memberName, "data");
        if (e != null) return e.getOffset();
        return -1; // not found
    }

    // ==================== Function Calls ====================

    // ---- 2.1, 2.2: Free function call as expression (rubric items 2.1, 2.2, 2.3) ----

    /**
     * Generates a free function call and returns the register holding the return value.
     *
     * Calling convention:
     *   1. Evaluate each argument and store it at the callee's expected stack offset.
     *      - Arrays/objects are passed by reference (their address is stored).
     *      - Scalars are passed by value.
     *      - Arguments are placed at -(8 + N*4 + frameSize) from current r14,
     *        so that after pushing the frame they appear at -8, -12, -16... from new r14.
     *   2. Push the callee's frame:  subi r14,r14,frameSize
     *   3. Jump-and-link:  jl r15,label  (saves return address in r15, jumps to function)
     *   4. Pop the frame:  addi r14,r14,frameSize
     *   5. Copy return value:  add rN,r0,r13
     */
    private String generateFuncCallExpr(ASTNode node, SymbolTable searchScope) {
        String fname = node.getChildren().get(0).getValue();
        ASTNode aparams = node.getChildren().get(1);

        emit("", "", "% Function call: " + fname + " (line " + node.getLineNumber() + ")");

        // Find the function entry
        SymbolTableEntry fe = null;
        if (searchScope != null) {
            fe = searchScope.lookupLocal(fname, "function");
            if (fe == null) fe = searchScope.lookupInherited(fname, "function");
        } else {
            for (SymbolTableEntry e : globalTable.getEntries())
                if ("function".equals(e.getKind()) && e.getName().equalsIgnoreCase(fname)) { fe = e; break; }
        }

        int frameSize = 0;
        if (fe != null && fe.getLink() != null) {
            frameSize = fe.getLink().getScopeSize();
        } else {
            frameSize = 200;
        }

        // Push arguments onto the new frame
        if (aparams != null && aparams.getChildren() != null) {
            // Get the param types from function signature to detect array params
            List<String> paramTypes = null;
            if (fe != null) paramTypes = getParamTypesFromSig(fe.getType());

            int paramOffset = -8; // first param at -8(new_r14)
            for (int i = 0; i < aparams.getChildren().size(); i++) {
                ASTNode arg = aparams.getChildren().get(i);
                boolean isArrayParam = (paramTypes != null && i < paramTypes.size()
                        && paramTypes.get(i).contains("["));
                boolean isObjectParam = false;
                if (paramTypes != null && i < paramTypes.size()) {
                    String pt = paramTypes.get(i).replaceAll("\\[.*", "");
                    isObjectParam = !pt.equals("int") && !pt.equals("float") && !pt.equals("void");
                }

                String argReg;
                if ((isArrayParam || isObjectParam) && "DataMember".equals(arg.getType())) {
                    // Pass by reference: pass the address of the array/object
                    argReg = generateVarAddress(arg);
                    emit("", "sw " + (paramOffset - frameSize) + "(r14)," + argReg,
                            "% Pass array/object address to function");
                } else {
                    argReg = generateExpr(arg);
                    emit("", "sw " + (paramOffset - frameSize) + "(r14)," + argReg,
                            "% Pass argument to function");
                }
                freeReg(argReg);
                paramOffset -= 4;
            }
        }

        // Adjust stack and call
        emit("", "subi r14,r14," + frameSize, "% Allocate frame for " + fname);
        String label = findFuncLabel(fname, searchScope);
        emit("", "jl r15," + label, "% Call " + fname);
        emit("", "addi r14,r14," + frameSize, "% Deallocate frame");

        // Result is in r13
        String resultReg = allocReg();
        emit("", "add " + resultReg + ",r0,r13", "% Get return value");
        return resultReg;
    }

    // ---- 2.4: Member function call (rubric item 2.4) ----

    /**
     * Generates a member function call: obj.method(args).
     *
     * Same as a free function call, but with one key addition: the object's memory address
     * is passed as a hidden first parameter at -8(new_r14). Inside the member function,
     * this is the "self pointer" used to access the object's data members.
     *
     * Steps:
     *   1. Compute the object's address (from the left side of the dot).
     *   2. Store it at -8 of the callee's frame (hidden 'self' parameter).
     *   3. Store explicit arguments starting at -12 of the callee's frame.
     *   4. Push frame, jl to ClassName::funcName, pop frame, grab r13.
     */
    private String generateMemberFuncCall(ASTNode dotNode) {
        ASTNode left = dotNode.getChildren().get(0);
        ASTNode funcCallNode = dotNode.getChildren().get(1);
        String fname = funcCallNode.getChildren().get(0).getValue();
        ASTNode aparams = funcCallNode.getChildren().get(1);

        emit("", "", "% Member function call: ." + fname + " (line " + dotNode.getLineNumber() + ")");

        // Get the object's address — we need to pass it so the function can access data members
        String objAddrReg = generateVarAddress(left);

        // Find the class table
        String leftType = inferTypeForCodeGen(left);
        SymbolTable classTable = null;
        SymbolTableEntry classEntry = null;
        if (leftType != null) {
            classEntry = findClass(leftType);
            if (classEntry != null) classTable = classEntry.getLink();
        }

        // Find function entry for frame size
        SymbolTableEntry fe = null;
        if (classTable != null) {
            fe = classTable.lookupLocal(fname, "function");
            if (fe == null) fe = classTable.lookupInherited(fname, "function");
        }

        int frameSize = 200;
        if (fe != null && fe.getLink() != null) {
            frameSize = fe.getLink().getScopeSize();
        }

        // Push the object address as the first hidden parameter
        emit("", "sw " + (-8 - frameSize) + "(r14)," + objAddrReg, "% Pass 'self' object address");
        freeReg(objAddrReg);

        // Push explicit arguments
        if (aparams != null && aparams.getChildren() != null) {
            int paramOffset = -12; // after the hidden 'self' parameter
            for (ASTNode arg : aparams.getChildren()) {
                String argReg = generateExpr(arg);
                emit("", "sw " + (paramOffset - frameSize) + "(r14)," + argReg, "% Pass argument");
                freeReg(argReg);
                paramOffset -= 4;
            }
        }

        // Call
        emit("", "subi r14,r14," + frameSize, "% Allocate frame for member " + fname);
        String label = findMemberFuncLabel(leftType, fname);
        emit("", "jl r15," + label, "% Call " + leftType + "::" + fname);
        emit("", "addi r14,r14," + frameSize, "% Deallocate frame");

        String resultReg = allocReg();
        emit("", "add " + resultReg + ",r0,r13", "% Get return value");
        return resultReg;
    }

    /** Function call used as a statement (return value is discarded). */
    private void generateFuncCallStatement(ASTNode node) {
        String reg = generateFuncCallExpr(node, null);
        freeReg(reg);
    }

    // ==================== Helper Methods ====================
    // Utility methods for label generation, type inference, symbol table lookups, etc.

    /**
     * Returns the current scope's total frame size. Used as the sub-frame offset when
     * calling library routines (intstr, putstr, etc.) — we push r14 down by this amount
     * so the library's -8(r14)/-12(r14) parameter slots don't overwrite our locals.
     */
    private int getLibCallOffset() {
        int frameSize = currentScope.getScopeSize();
        return frameSize;
    }

    /** Builds the Moon label for a function: "ClassName::funcName" or "::funcName". */
    private String findFuncLabel(String fname, SymbolTable searchScope) {
        if (searchScope != null) {
            // Member function
            return sanitizeLabel(searchScope.getName() + "::" + fname);
        }
        return sanitizeLabel("::" + fname);
    }

    private String findMemberFuncLabel(String className, String funcName) {
        return sanitizeLabel(className + "::" + funcName);
    }

    /**
     * Infers the type of an expression node for code generation purposes.
     * Used to determine if a variable is class-typed (needs object copy or address-based access)
     * and to look up class tables for member resolution in dot expressions.
     */
    private String inferTypeForCodeGen(ASTNode node) {
        if (node == null) return null;
        switch (node.getType()) {
            case "DataMember": {
                String name = node.getChildren().get(0).getValue();
                SymbolTableEntry e = lookupVar(name, currentScope);
                if (e != null) {
                    String type = e.getType();
                    // Strip array dims if indices used
                    ASTNode indiceList = node.getChildren().get(1);
                    int usedDims = (indiceList != null && indiceList.getChildren() != null) ? indiceList.getChildren().size() : 0;
                    if (usedDims > 0) return getBaseType(type);
                    return type;
                }
                return null;
            }
            case "Dot": {
                String leftType = inferTypeForCodeGen(node.getChildren().get(0));
                if (leftType == null) return null;
                SymbolTableEntry ce = findClass(leftType);
                if (ce == null || ce.getLink() == null) return null;
                ASTNode right = node.getChildren().get(1);
                if ("DataMember".equals(right.getType())) {
                    String mn = right.getChildren().get(0).getValue();
                    SymbolTableEntry me = ce.getLink().lookupLocal(mn, "data");
                    if (me == null) me = ce.getLink().lookupInherited(mn, "data");
                    return me != null ? me.getType() : null;
                }
                if ("FuncCall".equals(right.getType())) {
                    String fn = right.getChildren().get(0).getValue();
                    SymbolTableEntry fe = ce.getLink().lookupLocal(fn, "function");
                    if (fe == null) fe = ce.getLink().lookupInherited(fn, "function");
                    if (fe != null) return getReturnFromSig(fe.getType());
                }
                return null;
            }
            case "IntNum": return "int";
            case "FloatNum": return "float";
            default: return null;
        }
    }

    /**
     * Searches for a variable (local, param, or data member) by name, walking up the scope chain.
     * Checks inherited tables at each level (for class member access), then tries the parent scope.
     */
    private SymbolTableEntry lookupVar(String name, SymbolTable scope) {
        if (scope == null) return null;
        for (SymbolTableEntry e : scope.getEntries())
            if (e.getName().equalsIgnoreCase(name) && ("data".equals(e.getKind()) || "local".equals(e.getKind()) || "param".equals(e.getKind())))
                return e;
        for (SymbolTable it : scope.getInheritedTables()) {
            SymbolTableEntry e = lookupVar(name, it);
            if (e != null) return e;
        }
        return lookupVar(name, scope.getParent());
    }

    /** Looks up a class entry by name in the global symbol table. */
    private SymbolTableEntry findClass(String name) {
        if (name == null) return null;
        String base = name.replaceAll("\\[.*", "");
        for (SymbolTableEntry e : globalTable.getEntries())
            if ("class".equals(e.getKind()) && e.getName().equalsIgnoreCase(base)) return e;
        return null;
    }



    /** Returns the byte size of one element of a (possibly array) type (strips dimensions). */
    private int getElementSize(String type) {
        String base = type.replaceAll("\\[.*", "");
        switch (base) {
            case "int": return 4;
            case "float": return 4;
            default:
                SymbolTableEntry ce = findClass(base);
                return (ce != null && ce.getSize() > 0) ? ce.getSize() : 4;
        }
    }

    /** Extracts array dimensions from a type string, e.g., "int[3][4]" → [3, 4]. */
    private List<Integer> getDimensions(String type) {
        List<Integer> dims = new ArrayList<>();
        int idx = type.indexOf('[');
        while (idx >= 0) {
            int end = type.indexOf(']', idx);
            if (end > idx + 1) {
                try { dims.add(Integer.parseInt(type.substring(idx + 1, end))); }
                catch (NumberFormatException e) { dims.add(1); }
            } else {
                dims.add(1);
            }
            idx = type.indexOf('[', end + 1);
        }
        return dims;
    }

    /** Strips array dimensions to get the base type: "int[3]" → "int". */
    private String getBaseType(String type) {
        int b = type.indexOf('[');
        return b >= 0 ? type.substring(0, b) : type;
    }

    /** Extracts the return type from a function signature string like "(int,int):float" → "float". */
    private String getReturnFromSig(String sig) {
        if (sig == null) return null;
        int c = sig.lastIndexOf(':');
        return c >= 0 && c + 1 < sig.length() ? sig.substring(c + 1) : "";
    }

    /** Extracts parameter types from a signature: "(int,float[3]):void" → ["int", "float[3]"]. */
    private List<String> getParamTypesFromSig(String sig) {
        if (sig == null) return Collections.emptyList();
        int lp = sig.indexOf('('), rp = sig.indexOf(')');
        if (lp < 0 || rp < 0 || rp <= lp + 1) return Collections.emptyList();
        return Arrays.asList(sig.substring(lp + 1, rp).split(","));
    }

    /**
     * Finds the return type of the function currently being generated by searching
     * all function entries in the global table for the one whose link matches currentScope.
     */
    private String getReturnTypeOfCurrentFunc() {
        if (currentScope == null) return null;
        String scopeName = currentScope.getName();
        // Search all function entries to find the one whose link matches currentScope
        for (SymbolTableEntry e : globalTable.getEntries()) {
            if ("function".equals(e.getKind()) && e.getLink() == currentScope) {
                return getReturnFromSig(e.getType());
            }
            if ("class".equals(e.getKind()) && e.getLink() != null) {
                for (SymbolTableEntry me : e.getLink().getEntries()) {
                    if ("function".equals(me.getKind()) && me.getLink() == currentScope) {
                        return getReturnFromSig(me.getType());
                    }
                }
            }
        }
        return null;
    }

    /** Returns true if the scope is a member function (name like "ClassName::funcName", not "::funcName"). */
    private boolean isMemberFunction(SymbolTable scope) {
        if (scope == null) return false;
        String name = scope.getName();
        // Member functions have names like "ClassName::funcName" (not starting with "::")
        return name.contains("::") && !name.startsWith("::");
    }

    /** Extracts "ClassName" from a member function scope name "ClassName::funcName". */
    private String getMemberFuncClassName(SymbolTable scope) {
        String name = scope.getName();
        int idx = name.indexOf("::");
        return idx > 0 ? name.substring(0, idx) : "";
    }

    /** Returns true if the type is a class (not int, float, or void). */
    private boolean isClassType(String type) {
        if (type == null) return false;
        String base = type.replaceAll("\\[.*", "");
        return !base.equals("int") && !base.equals("float") && !base.equals("void") && !base.isEmpty();
    }

    // ==================== Data Labels for Variables ====================

    /**
     * Maps "scopeName_varName" → Moon label. Used for the global/fallback case where a
     * variable has no stack offset (offset=0). Reserves storage in the data section.
     */
    private final Map<String, String> globalVarLabels = new HashMap<>();

    /**
     * Returns a Moon label for a variable's data storage. If the variable hasn't been
     * assigned a label yet, creates one and emits a "res N" directive in the data section.
     * This is the fallback for variables without a stack offset (e.g., main locals at offset 0).
     */
    private String newDataLabelFor(String varName) {
        String scopeKey = currentScope.getName() + "_" + varName;
        if (globalVarLabels.containsKey(scopeKey)) return globalVarLabels.get(scopeKey);
        String label = sanitizeLabel(scopeKey);
        globalVarLabels.put(scopeKey, label);

        // Allocate storage in data section
        SymbolTableEntry entry = lookupVar(varName, currentScope);
        int size = 4;
        if (entry != null) size = typeSize(entry.getType());
        dataCode.append(label).append(" res ").append(size).append("\n");
        return label;
    }

    // ==================== Emit Helpers ====================

    /**
     * Appends one line of Moon assembly to execCode.
     * - Labels go at column 0 (on their own line if an instruction follows).
     * - Instructions are indented by 10 spaces.
     * - Comments are padded to column 40 for alignment.
     */
    private void emit(String label, String instr, String comment) {
        StringBuilder line = new StringBuilder();
        if (!label.isEmpty()) {
            line.append(label);
        }
        if (!instr.isEmpty()) {
            if (label.isEmpty()) {
                line.append("          ");
            } else {
                // Emit label on its own line, then instruction indented
                line.append("\n          ");
            }
            line.append(instr);
        }
        if (!comment.isEmpty()) {
            if (line.length() > 0) {
                int lastNl = line.lastIndexOf("\n");
                int col = (lastNl >= 0) ? line.length() - lastNl - 1 : line.length();
                while (col < 40) { line.append(' '); col++; }
            }
            line.append(comment);
        }
        execCode.append(line).append("\n");
    }

    // ==================== Register Allocation ====================

    /**
     * Simple register pool: regInUse[i] is true if ri is currently holding a live value.
     * r1 through r12 are available. r0, r13, r14, r15 are reserved.
     */
    private final boolean[] regInUse = new boolean[13]; // index 1..12

    /** Allocates the first free register from the r1..r12 pool. Falls back to r12 if all busy. */
    private String allocReg() {
        for (int i = 1; i <= 12; i++) {
            if (!regInUse[i]) {
                regInUse[i] = true;
                return "r" + i;
            }
        }
        // All registers in use — reuse r12 (spill would be better, but this is simple)
        return "r12";
    }

    /** Allocates a register and loads an immediate value into it. */
    private String allocRegWithValue(int value) {
        String reg = allocReg();
        emit("", "addi " + reg + ",r0," + value, "% Load constant " + value);
        return reg;
    }

    /** Marks a register as free so it can be reused by future allocReg() calls. */
    private void freeReg(String reg) {
        if (reg == null) return;
        if (reg.startsWith("r")) {
            try {
                int n = Integer.parseInt(reg.substring(1));
                if (n >= 1 && n <= 12) regInUse[n] = false;
            } catch (NumberFormatException e) {}
        }
    }

    // ==================== Label Generation ====================

    /** Generates a unique control-flow label like "while0", "else3", "endif4". */
    private String newLabel(String prefix) {
        return prefix + (labelCounter++);
    }

    /** Generates a unique data label like "buf0", "rbuf1", "objret2". */
    private String newDataLabel(String prefix) {
        return prefix + (tempCounter++);
    }

    /** Converts a scope name (e.g., "MyClass::method") to a valid Moon label (alphanumeric + underscore). */
    private String sanitizeLabel(String s) {
        return s.replaceAll("[^a-zA-Z0-9_]", "_").replaceAll("^_+", "f_");
    }

    // ==================== Moon Library (inline) ====================

    /**
     * Appends the four I/O library routines directly into the data section.
     * These are small loops written in Moon assembly, based on the standard lib.m
     * by Peter Grogono. They're inlined so the generated .moon file is self-contained
     * (no external library file needed).
     *
     *   putstr: prints a null-terminated string character by character (via putc).
     *   getstr: reads characters from keyboard (via getc) until newline, null-terminates.
     *   strint: converts a digit string to an integer (handles sign, skips leading spaces).
     *   intstr: converts an integer to a digit string (right-to-left in a buffer).
     *
     * All routines use the same calling convention:
     *   -8(r14) = first argument, -12(r14) = second argument
     *   r13 = return value, r15 = return address (jr r15 to return)
     */
    private void emitLibrary() {
        dataCode.append("\n% ==========================================\n");
        dataCode.append("% Moon Library (putstr, getstr, intstr, strint)\n");
        dataCode.append("% ==========================================\n");
        dataCode.append("          align\n");

        // putstr
        dataCode.append("putstr    lw r1,-8(r14)\n");
        dataCode.append("          addi r2,r0,0\n");
        dataCode.append("putstr1   lb r2,0(r1)\n");
        dataCode.append("          ceqi r3,r2,0\n");
        dataCode.append("          bnz r3,putstr2\n");
        dataCode.append("          putc r2\n");
        dataCode.append("          addi r1,r1,1\n");
        dataCode.append("          j putstr1\n");
        dataCode.append("putstr2   jr r15\n");

        // getstr
        dataCode.append("getstr    lw r1,-8(r14)\n");
        dataCode.append("getstr1   getc r2\n");
        dataCode.append("          ceqi r3,r2,10\n");
        dataCode.append("          bnz r3,getstr2\n");
        dataCode.append("          sb 0(r1),r2\n");
        dataCode.append("          addi r1,r1,1\n");
        dataCode.append("          j getstr1\n");
        dataCode.append("getstr2   sb 0(r1),r0\n");
        dataCode.append("          jr r15\n");

        // strint (string to integer)
        dataCode.append("strint    addi r13,r0,0\n");
        dataCode.append("          addi r4,r0,0\n");
        dataCode.append("          lw r1,-8(r14)\n");
        dataCode.append("          addi r2,r0,0\n");
        dataCode.append("strint1   lb r2,0(r1)\n");
        dataCode.append("          cnei r3,r2,32\n");
        dataCode.append("          bnz r3,strint2\n");
        dataCode.append("          addi r1,r1,1\n");
        dataCode.append("          j strint1\n");
        dataCode.append("strint2   cnei r3,r2,43\n");
        dataCode.append("          bnz r3,strint3\n");
        dataCode.append("          j strint4\n");
        dataCode.append("strint3   cnei r3,r2,45\n");
        dataCode.append("          bnz r3,strint5\n");
        dataCode.append("          addi r4,r4,1\n");
        dataCode.append("strint4   addi r1,r1,1\n");
        dataCode.append("          lb r2,0(r1)\n");
        dataCode.append("strint5   clti r3,r2,48\n");
        dataCode.append("          bnz r3,strint6\n");
        dataCode.append("          cgti r3,r2,57\n");
        dataCode.append("          bnz r3,strint6\n");
        dataCode.append("          subi r2,r2,48\n");
        dataCode.append("          muli r13,r13,10\n");
        dataCode.append("          add r13,r13,r2\n");
        dataCode.append("          j strint4\n");
        dataCode.append("strint6   ceqi r3,r4,0\n");
        dataCode.append("          bnz r3,strint7\n");
        dataCode.append("          sub r13,r0,r13\n");
        dataCode.append("strint7   jr r15\n");

        // intstr (integer to string)
        dataCode.append("intstr    lw r13,-12(r14)\n");
        dataCode.append("          addi r13,r13,11\n");
        dataCode.append("          sb 0(r13),r0\n");
        dataCode.append("          lw r1,-8(r14)\n");
        dataCode.append("          addi r2,r0,0\n");
        dataCode.append("          cgei r3,r1,0\n");
        dataCode.append("          bnz r3,intstr1\n");
        dataCode.append("          addi r2,r2,1\n");
        dataCode.append("          sub r1,r0,r1\n");
        dataCode.append("intstr1   addi r3,r1,0\n");
        dataCode.append("          modi r3,r3,10\n");
        dataCode.append("          addi r3,r3,48\n");
        dataCode.append("          subi r13,r13,1\n");
        dataCode.append("          sb 0(r13),r3\n");
        dataCode.append("          divi r1,r1,10\n");
        dataCode.append("          cnei r3,r1,0\n");
        dataCode.append("          bnz r3,intstr1\n");
        dataCode.append("          ceqi r3,r2,0\n");
        dataCode.append("          bnz r3,intstr2\n");
        dataCode.append("          subi r13,r13,1\n");
        dataCode.append("          addi r3,r0,45\n");
        dataCode.append("          sb 0(r13),r3\n");
        dataCode.append("intstr2   jr r15\n");
    }
}
